/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CostRouteImport } from './routes/cost'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FrontDeskRouteImport } from './routes/front-desk'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TheTeamRouteImport } from './routes/the-team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontDeskRoute = FrontDeskRouteImport.update({
  id: '/front-desk',
  path: '/front-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TheTeamRoute = TheTeamRouteImport.update({
  id: '/the-team',
  path: '/the-team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/contact': typeof ContactRoute
  '/cost': typeof CostRoute
  '/design-system': typeof DesignSystemRoute
  '/faq': typeof FaqRoute
  '/front-desk': typeof FrontDeskRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/the-team': typeof TheTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/contact': typeof ContactRoute
  '/cost': typeof CostRoute
  '/design-system': typeof DesignSystemRoute
  '/faq': typeof FaqRoute
  '/front-desk': typeof FrontDeskRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/the-team': typeof TheTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/contact': typeof ContactRoute
  '/cost': typeof CostRoute
  '/design-system': typeof DesignSystemRoute
  '/faq': typeof FaqRoute
  '/front-desk': typeof FrontDeskRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/the-team': typeof TheTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliates'
    | '/contact'
    | '/cost'
    | '/design-system'
    | '/faq'
    | '/front-desk'
    | '/resources'
    | '/services'
    | '/the-team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliates'
    | '/contact'
    | '/cost'
    | '/design-system'
    | '/faq'
    | '/front-desk'
    | '/resources'
    | '/services'
    | '/the-team'
  id:
    | '__root__'
    | '/'
    | '/affiliates'
    | '/contact'
    | '/cost'
    | '/design-system'
    | '/faq'
    | '/front-desk'
    | '/resources'
    | '/services'
    | '/the-team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliatesRoute: typeof AffiliatesRoute
  ContactRoute: typeof ContactRoute
  CostRoute: typeof CostRoute
  DesignSystemRoute: typeof DesignSystemRoute
  FaqRoute: typeof FaqRoute
  FrontDeskRoute: typeof FrontDeskRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  TheTeamRoute: typeof TheTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/front-desk': {
      id: '/front-desk'
      path: '/front-desk'
      fullPath: '/front-desk'
      preLoaderRoute: typeof FrontDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-team': {
      id: '/the-team'
      path: '/the-team'
      fullPath: '/the-team'
      preLoaderRoute: typeof TheTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliatesRoute: AffiliatesRoute,
  ContactRoute: ContactRoute,
  CostRoute: CostRoute,
  DesignSystemRoute: DesignSystemRoute,
  FaqRoute: FaqRoute,
  FrontDeskRoute: FrontDeskRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  TheTeamRoute: TheTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
